# Generated by Django 3.1.13 on 2021-07-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_auto_20210716_1926"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="description",
            field=models.TextField(default=" ", max_length=255),
            preserve_default=False,
        ),
    ]
