# Generated by Django 3.1.13 on 2021-07-21 12:31

import core.models
import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_achievement_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="created_at",
            field=core.models.AutoDateTimeField(default=django.utils.timezone.now),
        ),
    ]
