# Generated by Django 3.1.13 on 2021-07-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_auto_20210721_1424"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_id",
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
