# Generated by Django 3.1.13 on 2021-07-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_user_telegram_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="telegram_id",
        ),
        migrations.AddField(
            model_name="boec",
            name="telegram_id",
            field=models.IntegerField(
                null=True, unique=True, verbose_name="Telegram ID"
            ),
        ),
    ]
