# Generated by Django 3.1.13 on 2021-07-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_auto_20210726_0025"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boec",
            name="telegram_id",
            field=models.IntegerField(
                blank=True, null=True, unique=True, verbose_name="Telegram ID"
            ),
        ),
    ]
