# Generated by Django 3.1.13 on 2021-07-28 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_auto_20210728_1948"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="vkId",
            new_name="vk_id",
        ),
    ]
