# Generated by Django 3.1.13 on 2021-07-28 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_auto_20210728_1949"),
    ]

    operations = [
        migrations.RenameField(
            model_name="boec",
            old_name="vkId",
            new_name="vk_id",
        ),
    ]
