# Generated by Django 3.1.13 on 2021-07-28 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_auto_20210728_1951"),
    ]

    operations = [
        migrations.RenameField(
            model_name="area",
            old_name="shortTitle",
            new_name="short_title",
        ),
        migrations.RenameField(
            model_name="boec",
            old_name="DOB",
            new_name="date_of_birth",
        ),
        migrations.RenameField(
            model_name="boec",
            old_name="firstName",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="boec",
            old_name="lastName",
            new_name="last_name",
        ),
        migrations.RenameField(
            model_name="boec",
            old_name="middleName",
            new_name="middle_name",
        ),
        migrations.RenameField(
            model_name="boec",
            old_name="unreadActivityCount",
            new_name="unread_activity_count",
        ),
        migrations.RenameField(
            model_name="brigade",
            old_name="DOB",
            new_name="date_of_birth",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="isCanonical",
            new_name="is_canonical",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="isTicketed",
            new_name="is_ticketed",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="startDate",
            new_name="start_date",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="startTime",
            new_name="start_time",
        ),
    ]
