# Generated by Django 3.1.13 on 2021-07-28 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_auto_20210728_1954"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="createdAt",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="updatedAt",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="ticketscan",
            old_name="createdAt",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="ticketscan",
            old_name="isFinal",
            new_name="is_final",
        ),
        migrations.RenameField(
            model_name="ticketscan",
            old_name="updatedAt",
            new_name="updated_at",
        ),
    ]
