# Generated by Django 3.1.13 on 2021-07-28 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_auto_20210728_1956"),
    ]

    operations = [
        migrations.RenameField(
            model_name="nomination",
            old_name="isRated",
            new_name="is_rated",
        ),
        migrations.RenameField(
            model_name="nomination",
            old_name="sportPlace",
            new_name="sport_place",
        ),
        migrations.RenameField(
            model_name="participant",
            old_name="isApproved",
            new_name="is_approved",
        ),
        migrations.RenameField(
            model_name="position",
            old_name="fromDate",
            new_name="from_date",
        ),
        migrations.RenameField(
            model_name="position",
            old_name="toDate",
            new_name="to_date",
        ),
        migrations.RenameField(
            model_name="season",
            old_name="isAccepted",
            new_name="is_accepted",
        ),
        migrations.RenameField(
            model_name="season",
            old_name="isCandidate",
            new_name="is_candidate",
        ),
    ]
