# Generated by Django 3.1.13 on 2021-07-31 12:21

import django_fsm
from django.db import migrations


def migrate_status_to_state(apps, schema_editor):
    Event = apps.get_model("core", "Event")
    for event in Event.objects.all():
        if event.status == 1:
            event.state = 6
            event.save()
        elif event.status == 2:
            event.state = 7
            event.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_auto_20210728_2000"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="state",
            field=django_fsm.FSMIntegerField(default=0),
        ),
        migrations.RunPython(migrate_status_to_state),
    ]
