# Generated by Django 3.1.13 on 2021-07-31 21:24

import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_event_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (0, "Мероприятие создано"),
                    (1, "Расчёт квот"),
                    (2, "Распределение квот"),
                    (3, "Регистрация желающих"),
                    (4, "Регистрация окончена"),
                    (5, "Билеты сгенерированы"),
                    (6, "Мероприятие прошло"),
                    (7, "Мероприятие отменено"),
                ],
                default=0,
                verbose_name="Статус мероприятия",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.IntegerField(verbose_name="Статус мероприятия (deprecated)"),
        ),
        migrations.CreateModel(
            name="EventQuota",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "count",
                    models.IntegerField(
                        default=None, null=True, verbose_name="Количество мест"
                    ),
                ),
                (
                    "brigade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.brigade",
                        verbose_name="Отряд",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="core.event",
                        verbose_name="Мероприятие",
                    ),
                ),
            ],
            options={
                "verbose_name": "Квота отряда",
                "verbose_name_plural": "Квоты отрядов",
            },
        ),
    ]
