# Generated by Django 3.1.13 on 2021-08-01 10:33

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_auto_20210801_0024"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="status",
        ),
        migrations.AlterField(
            model_name="event",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (0, "Мероприятие создано"),
                    (1, "Расчёт квот"),
                    (3, "Регистрация желающих"),
                    (4, "Регистрация окончена"),
                    (5, "Билеты сгенерированы"),
                    (6, "Мероприятие прошло"),
                    (7, "Мероприятие отменено"),
                ],
                default=0,
                verbose_name="Статус мероприятия",
            ),
        ),
    ]
