# Generated by Django 3.1.13 on 2021-08-01 10:55

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_auto_20210801_1333"),
    ]

    operations = [
        migrations.AddField(
            model_name="brigade",
            name="last_festival_state",
            field=models.CharField(
                choices=[
                    ("candidate", "Кандидатский"),
                    ("member", "Действующий"),
                    ("dead", "Мёртвый"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="brigade",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("candidate", "Кандидатский"),
                    ("member", "Действующий"),
                    ("dead", "Мёртвый"),
                ],
                default="candidate",
                max_length=50,
                verbose_name="Статус отряда",
            ),
        ),
    ]
