# Generated by Django 3.1.13 on 2021-08-15 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_auto_20210801_1355"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventquota",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotas",
                to="core.event",
                verbose_name="Мероприятие",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="brigade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="event_participants",
                to="core.brigade",
                verbose_name="Отряд",
            ),
        ),
    ]
