# Generated by Django 3.1.13 on 2021-08-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_auto_20210815_1152"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brigade",
            name="last_festival_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("candidate", "Кандидатский"),
                    ("member", "Действующий"),
                    ("dead", "Мёртвый"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
