# Generated by Django 3.1.13 on 2021-08-15 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_auto_20210815_1308"),
    ]

    operations = [
        migrations.AddField(
            model_name="brigade",
            name="custom_area_prefix",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="brigade",
            name="area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="brigades",
                to="core.area",
                verbose_name="Направление",
            ),
        ),
        migrations.AlterField(
            model_name="brigade",
            name="shtab",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="core.shtab",
                verbose_name="Штаб",
            ),
        ),
        migrations.AlterField(
            model_name="brigade",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
    ]
