# Generated by Django 3.1.13 on 2021-08-24 17:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_auto_20210815_1314"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoteAnswer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(default=django.utils.timezone.now)),
                ("text", models.CharField(max_length=255)),
                ("voted", models.ManyToManyField(blank=True, to="core.Boec")),
            ],
            options={
                "verbose_name": "Ответ голосования",
                "verbose_name_plural": "Ответы голосования",
            },
        ),
        migrations.CreateModel(
            name="VoteQuestion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(default=django.utils.timezone.now)),
                ("text", models.CharField(max_length=255)),
                ("answers", models.ManyToManyField(blank=True, to="core.VoteAnswer")),
            ],
            options={
                "verbose_name": "Вопрос голосования",
                "verbose_name_plural": "Вопросы голосования",
            },
        ),
        migrations.CreateModel(
            name="Voting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(default=django.utils.timezone.now)),
                ("text", models.CharField(max_length=255)),
                (
                    "questions",
                    models.ManyToManyField(blank=True, to="core.VoteQuestion"),
                ),
            ],
            options={
                "verbose_name": "Голосование",
                "verbose_name_plural": "Голосования",
            },
        ),
    ]
